### ISSUE TITLE
Won't work on Xcode Version 7.0 (7A218)

### ISSUE THREAD

**Issue by ghost** [wiruzx/QuickJump#11]
Tried to reinstall but it's no changes.
Any suggestions ?

**Comment by wiruzx** [comment]
Should be fixed now

**Comment by ghost** [comment]
now it's loading (xcode ask to load new bundle)
I configurate keystroke, but when i pressed it - i just heard default os x sound - like nothing possible to do.

**Comment by wiruzx** [comment]
@sacred0x01 in the new version I have changed the title for keystroke in settings.
Please, take a look at https://github.com/wiruzx/QuickJump#version-11

Basically, what you need to do, is to change `Toggle QuickJump` to `QuickJump: char mode` in keyboard settings.

**Comment by ghost** [comment]
but as i mentioned before - i've already changed keystroke, but it didn't help

**Comment by wiruzx** [comment]
Do you see your keystroke in `Editor -> QuickJump` menu, near the "QuickJump: char mode"?

**Comment by ghost** [comment]
Nope. So strange

**Comment by wiruzx** [comment]
Check your keyboard settings title again. May be there is extra space after the title or some typo.
If everything is correct, there may be some conflicts with existing Xcode keystroke. Try to set some unused one

**Comment by ghost** [comment]
Ok, thx for support. I will notify u later when receive results

**Comment by ghost** [comment]
Hello again
https://www.dropbox.com/s/ygxwwrpl16fsw6a/Screenshot%202015-09-30%2009.19.31.png?dl=0
just check this - all the requirements done right, but plugin still not working. Are u using it by yourself ?

**Comment by wiruzx** [comment]
Hi @sacred0x01 
May be the problem in `F3` key? Could you try to set another keystroke? `Ctrl+;` for example(I'm using this one right now).

**Comment by ghost** [comment]
The same result. Pretty weird. Heh(

**Comment by wiruzx** [comment]
Are you using El Capitan?

**Comment by ghost** [comment]
Yes

**Comment by wiruzx** [comment]
I haven't test it on El Capitan yet. I'll take a look when I got home. But I suppose it OSX's shortcuts problem.

**Comment by ghost** [comment]
Okay, hope so. Thx man
