### ISSUE TITLE
Xcode 7.0.1 cannot launch after setting `command-;` as a shortcut

### ISSUE THREAD

**Issue by yam-liu** [wiruzx/QuickJump#13]
I install this from alcatraz.
QuickJump can be used immediately, but not the next launch of Xcode. Actually it blocks the next launch.
I have tried remove my plugins and just leave this, Xcode still cannot launch, finally results in not responding.
Maybe you can not reproduce this issue, but please me know if you need some other details.

**Comment by wiruzx** [comment]
Could you please try this in Xcode 7.1?

**Comment by wiruzx** [comment]
I also wonder if this might be an alcatraz issue

**Comment by yam-liu** [comment]
Sadly, it still has the issue when I build manually.
I didn't try Xcode 7.1, because I am using Yosemite and cannot upgrade to El Capitan recently.

**Comment by wiruzx** [comment]
@ooopscc I'm also using Yosemite and tried both Xcode 7.0 and 7.1 and everything worked fine. Are there any other plugins in your Xcode installed?

**Comment by yam-liu** [comment]
But I have tried just leave this one installed. No other plugins bothered. It's so wired...  Is there an approach to see what is happening when launching Xcode?

**Comment by wiruzx** [comment]
Could you run Xcode from the terminal and see what it will print?

Like so, depending on where your Xcode is located:

```
/Applications/Xcode.app/Contents/MacOS/Xcode
```

**Comment by yam-liu** [comment]
```
/Applications/Xcode.app/Contents/MacOS/Xcode
2015-10-23 21:49:12.336 Xcode[13002:1524559] Updating Repo: /Users/davel/Library/Application Support/Alcatraz/Plug-ins/Alcatraz
2015-10-23 21:49:13.064 Xcode[13002:1524547] *** -[NSLock lock]: deadlock (<NSLock: 0x7ff29e9d1a60> 'NSMenuKEUniquing lock')
2015-10-23 21:49:13.065 Xcode[13002:1524547] *** Break on _NSLockError() to debug.
[1]    13002 terminated  /Applications/Xcode.app/Contents/MacOS/Xcode
```

I found something interesting.
The last line is I force quit Xcode.
I think I know why this happens, the shortcut is not unique...
I use `command+;` as the key because I use quickjump in Sublime Text or maybe Intellij IDEA.

Could you tell why this key not uniquing? I have removed the conflict keys in Xcode. And is it possible to set a shortcut key in Xcode scope not global?

**Comment by wiruzx** [comment]
I think the problem here is in alcatraz rather than shortcuts. Could you remove alcatraz and try this again?

**Comment by yam-liu** [comment]
In the first issue description, I have already tried this.
It is really the shortcut problem. You can use `command+;` to reproduce this issue.
so,

> Could you tell why this key not uniquing? I have removed the conflict keys in Xcode. And is it possible to set a shortcut key in Xcode scope not global?

I don't know more about the unique key.

**Comment by wiruzx** [comment]
@ooopscc No, I mean try to run it from the terminal with removed Alcatraz

**Comment by wiruzx** [comment]
@ooopscc I see what you mean. I was able to reproduce that
