### ISSUE TITLE
Xcode 7.2 support

### ISSUE THREAD

**Issue by wiruzx** [wiruzx/QuickJump#14]

**Comment by vojkodrev** [comment]
It still does not work when I install it with Alcatraz (http://alcatraz.io). My Xcode version is 7.2 (7C68).

**Comment by wiruzx** [comment]
I'll take a look

**Comment by wiruzx** [comment]
@vojkodrev Should be fixed now. Try to reinstall it.

**Comment by vojkodrev** [comment]
It works now. Extension installed without a problem. Thanks for quick response.
