### ISSUE TITLE
Support Xcode 7.3.1?

### ISSUE THREAD

**Issue by gngrwzrd** [wiruzx/QuickJump#16]
I really like the idea of this plugin, I was going to write something myself until I found this. I'm using Xcode 7.3.1. I've installed through Alcatraz and restarted Xcode. I don't see any menu items for it. 

I was able to find in the source where it's adding the menu items to the Editor menu. But it doesn't seem to work?

Thanks!

**Comment by wiruzx** [comment]
@gngrwzrd Could you try to install it manually please?

**Comment by wiruzx** [comment]
I see what's the problem.
For now you cannot install QuickJump via Alcatraz, because it [doesn't support submodules](https://github.com/alcatraz/Alcatraz/issues/454)
But you can still install it manually.
