### ISSUE TITLE
Build failed in Xcode 8.

### ISSUE THREAD

**Issue by xdidi3r** [wiruzx/QuickJump#18]
When i open `QuickJump.xcodeproj` in Xcode 8, the infomation below show to me.
> The targets “QuickJump” and “QuickJumpTests” contain source code developed with an earlier version of Swift.
> Choose “Convert” to update the source code in this project to the latest SDKs. You will be given the choice to use Swift 2.3 syntax or update to Swift 3.
> This action can be performed later using “Convert to Current Swift Syntax” in the Edit menu.

And the project build failed.
![Uploading 88F80DB4-E592-4416-98A3-8678468DD511.png…]()

**Comment by xdidi3r** [comment]
![88f80db4-e592-4416-98a3-8678468dd511](https://cloud.githubusercontent.com/assets/23443899/21709584/071144c4-d41d-11e6-8ec6-dafefe0b9a8f.png)

**Comment by wiruzx** [comment]
Thanks @xdidi3r , I'll look into it

**Comment by wiruzx** [comment]
It should be fixed now
