### ISSUE TITLE
Does this work with xcode 10.0?

### ISSUE THREAD

**Issue by kylpo** [wiruzx/QuickJump#21]
Pretty sure I had this working in xcode 9. With the latest update, I haven't gotten it to work.

Thanks for any response.

**Comment by wiruzx** [comment]
@kylpo Hey, could you try now please?

**Comment by kylpo** [comment]
Sorry for the slow response, @wiruzx. I have pulled the latest, `clean`ed, and `build` successfully. After an xcode restart, when I use my `cmd j` shortcut for `QuickJump: char mode`, I just hear an error sound.

I'm new to using xcode in general, so I'm not sure how to troubleshoot or provide helpful info for you. In Mac's `Console`, the only relevant log is:

```
687: -> Incoming Request : actionID 4096, inClientPID 49505(Xcode), inBehavior 1, customVibeDataProvided 0, loop 0, loopPeriod 0.000000, inFlags 0, inClientCompletionToken 11
```

Please let me know if you have any tips for troubleshooting the problem. Thanks for your help and work on this!
