### ISSUE TITLE
Xcode 7 problem

### ISSUE THREAD

**Issue by ghost** [wiruzx/QuickJump#6]
It seems to be not working with Xcode 7 beta 4.

**Comment by wiruzx** [comment]
Yeah, that's because, every UDID of every new version of Xcode should be included into `DVTPlugInCompatibilityUUIDs` list into `Info.plist` file.
If you like, you could send me PR, or wait, until I download new Xcode :)

**Comment by ghost** [comment]
Where i can find Xcode 7 UDID ?

**Comment by wiruzx** [comment]
@sacred0x01 you could run `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID` with path to your Xcode

**Comment by ghost** [comment]
I've got it. You can close this ticket

**Comment by wiruzx** [comment]
Thanks!
