### ISSUE TITLE
Can QuickJump work as EasyMotion?

### ISSUE THREAD

**Issue by JGideon** [wiruzx/QuickJump#8]
EasyMotion is a plugin in vim that can easily move cursor in a short distance.
Example:
when I toggle the function of EasyMotion, it works like this:
![image](https://cloud.githubusercontent.com/assets/5210791/9457965/44484004-4b1b-11e5-9a5c-65b4079b63d7.png)
I think it may be more useful for me.

**Comment by wiruzx** [comment]
Hi @JGideon. I haven't used EasyMotion, could you please explain how does this work? Does it highlight characters in several lines around the cursor or in the lexical scope?

**Comment by JGideon** [comment]
When I type ,,w to trigger the word motion, EasyMotion will highlight the first letter from the cursor in several rows. So I can easily move the cursor in a short distance.The project : https://github.com/easymotion/vim-easymotion

**Comment by wiruzx** [comment]
Now I see what you meant. I'm afraid this is not possible in the current implementation, and it is not the thing that can be done very quickly, so maybe when I'll have more free time, I'll implement that. Thanks!
